name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/resonancecascade1/ubuntu:main
    strategy:
      matrix:
        foo: [1,2,3,4,5]
        bar: [1,2,3,4]
    steps:
      - run: gcc --version
